### ISSUE TITLE
eBot mySQL (docker)

### ISSUE THREAD

**Issue by mrc4tt** [jffz/docker-ebot#5]
Hi @jffz 

Do you have some idea/tips for remote connection allow on docker's IP?

2018-10-27T10:19:45.856978Z 3 [Note] Access denied for user 'ebotv3'@'172.17.0.3' (using password: YES)
2018-10-27T10:19:45.938861Z 4 [Note] Access denied for user 'ebotv3'@'172.17.0.3' (using password: YES)

As example. ^^_^^

What can i do?

**Comment by jffz** [comment]
Looks like you are using a wong password or trying to access a database you don't have perms on.

**Comment by mrc4tt** [comment]
Hmm. i did set the configuration (on docker-compose) correct with "user root". i will try again! :D

**Comment by mrc4tt** [comment]
Got it fixed! :D the problem was, it will not "create" database, because using mariadb > where it often says: Specified key was too long. Maximum key length is 767 mysql
