### ISSUE TITLE
Docker <-> nginx/proxy reserved(subdomain?)

### ISSUE THREAD

**Issue by mrc4tt** [jffz/docker-ebot#6]
Hi,

Do you have worked to get "ebot" to running via subdomain of using "proxy reserved? - via ngix"?

I don't know, what i can do, for getting it works for:
1) IP:8080 => ebotweb works fine there. (where it have sucessfull contact to the server!)
2) ebot.domain => ebotweb works. but there is no "online" (Here where i'm using proxy reserved, where it don't contact the server!)

**Maybe you have some idea, for about it will works via proxy-reserved on nginx for connection/using subdomain, without to use: http://real-IPAddress:8080**

Screenshot 1):
![](https://i.gyazo.com/5fa359bf86e8235b43b2554f6bb52c2f.png)

Screenshot 2):
![](https://i.gyazo.com/02ed88639bf735db86140816ae25659f.png)

nginx proxyconfig:
```
        # reverse proxy
        location / {
                proxy_pass http://127.0.0.1:8080;
                proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;
proxy_cache_bypass $http_upgrade;
proxy_set_header Accept-Encoding "";
        proxy_pass_request_headers      on;

        }
}
```

**Comment by H0K3R0** [comment]
Because websocket can't work on https.
http://forum.esport-tools.net/d/64-websockets-down

**Comment by H0K3R0** [comment]
Sorry for the mistake, pull request #131 solved your issue:
https://github.com/deStrO/eBot-CSGO/pull/131
